# Generated by Django 3.2.3 on 2022-01-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Benefits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
