# Generated by Django 3.2.3 on 2022-01-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Application_field',
            field=models.TextField(blank=True, null=True),
        ),
    ]
