# Generated by Django 3.2.3 on 2022-01-19 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220119_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.location'),
        ),
    ]
