# Generated by Django 3.2.3 on 2022-01-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Application_field',
            new_name='application_field',
        ),
    ]
