# Generated by Django 3.2.3 on 2022-01-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_benefits_product_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
