# Generated by Django 3.2.3 on 2022-01-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealers',
            old_name='company_name',
            new_name='dealer_name',
        ),
        migrations.RenameField(
            model_name='dealers',
            old_name='name',
            new_name='hardware_name',
        ),
    ]
