# Generated by Django 3.2.3 on 2022-01-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_category_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'slug')},
        ),
    ]
