# Generated by Django 3.2.3 on 2022-01-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20220119_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
